### ISSUE TITLE
ZIP files not loading properly in MeatPacker code commit 90c13433622b755572fc71f2fde32cf5ac162c8e

### ISSUE THREAD

**Issue by NickWeintraut** [Impro-Visor/lstmprovisor-java#1]
Everything works fine with a normal folder, but as soon as I zip it and try to load from that, I get this error:

`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at nickd4j.ReadWriteUtilities.getINDArray(ReadWriteUtilities.java:44)
    at nickd4j.ReadWriteUtilities.readNumpyCSVReader(ReadWriteUtilities.java:37)
    at architecture.NetworkMeatPacker.refresh(NetworkMeatPacker.java:76)
    at architecture.NetworkMeatPacker.pack(NetworkMeatPacker.java:30)
    at main.Driver.main(Driver.java:132)
Exception in thread "main" java.lang.NullPointerException
    at main.Driver.main(Driver.java:133)
Java Result: 1`

Commit 984fbe11e96b9c19b7207189c45ba7b6485ed908 attempts to rectify this by filtering out ".DS_Store" in filters (as that needed to be fixed anyways), but made no change in the error.

**Comment by danieldjohnson** [comment]
Don't zip the folder. Select all of the files in the folder and zip them instead. That should make it possible to load zips.

In general, I think the solution is to just not put .DS_Store in the zips. The python scripts to transfer weights over are set up to do this already. In the future I don't think we should ever have folders of csv files, we should just generate and use the zip files. (Also adding a special case just to deal with Mac OS bugs seems like a bad and unnecessary workaround.)

Given that, I think this is not really an issue that needs to be addressed. Thoughts?

**Comment by NickWeintraut** [comment]
Sweet! That sounds good.
